### ISSUE TITLE
generate response issue

### ISSUE THREAD

**Issue by PythonX-001** [Qewertyy/Open-API#2]
### error code :
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\lexica\core.py", line 45, in _request
    raise Exception(f"API error {response.text}")
Exception: API error {"message":"Internal Server Error","code":0}

**Comment by Qewertyy** [comment]
okay, will see

**Comment by Qewertyy** [comment]
fixed

**Comment by PythonX-001** [comment]
> fixed

im sorry but the image generate.py script still have the responce error . do this feature  work anymore ?
